upstream backend {
    server stable-version:80 weight=90;
    server canary-version:80 weight=10;
}

upstream backend_sticky {
    hash $cookie_canary consistent;
    server stable-version:80;
    server canary-version:80;
}
