ServerRoot "/etc/httpd"            # Base directory for all Apache config files
DocumentRoot "/var/www/html"       # Where website files are served from by default
Listen 80                          # Port Apache listens on
